In [1]:
def isnum(n):
    n = str(n)
    if n.isdigit():
        return True
    return False
li =["10","20","a"]
a =map(isnum,li)
list(a)


[True, True, False]

In [2]:
a=filter(isnum,li)
list(a)

['10', '20']

# lamda

In [1]:
def sum1(a,b):
    c=a+b
    return c
sum1(8,6)


14

In [4]:
a = lambda x,y :x+y
a(8,6)

14

In [5]:
s =lambda x:x**2
s(3)

9

In [1]:
a = int(input()) 
for i in range(0,a+1):
    print(i**2)

123
0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000
10201
10404
10609
10816
11025
11236
11449
11664
11881
12100
12321
12544
12769
12996
13225
13456
13689
13924
14161
14400
14641
14884
15129


### list comprehension

In [41]:
a = int(input())
for i in range(0,a+1):
    print(i**2)
    

1
0
1


In [38]:
a = [i**2 for i in range(1,11)]
a


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [6]:
### factorial of a number
a = int(input())
b=1
for i in range(1,a+1):
    b *=i
print(b)

5
120


In [40]:
# factorial of a number using function
import math
s = [math.factorial(i) for i in range(1,10)]
s

[1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

In [29]:
a = int(input())
b=1
for i in range(1,a+1):
    b *=i
print(b)

6
720


#### File Handling

* file handling is nothing but performing operations on a file
* entering some data to a file is called as writing a file
* retriving data  from a file is called as reading a file
* we can perform append,delete operations on files



In [17]:
def writetoafile(filename,data):
    with open(filename,"w") as f:
        f.write(data)
        return
filename ="data.txt"
writetoafile(filename,"line1\nline2\n")   
    

In [21]:
def readfromfile(filename):
    with open(filename,"r") as f:
        fd = f.read()
        f.close()
    return fd
filename = "data.txt"
readfromfile("data.txt")
def printlines(filename):
    with open(filename,"r") as f:
        for line in f:
            print(line,end =" ")
        return
printlines(filename)
print(readfromfile(filename))


line1
 line2
 line1
line2



In [20]:
def readfromfile(filename):
    with open(filename,"r")as f:
        fd = f.read()
        f.close()
    return fd
readfromfile("data.txt")

'line1\nline2\n'

In [23]:
def appendtofile(filename,data):
    with open(filename,"a") as f:
        for line in data:
            f.write("\n"+line)
        return
data=["line3","line4","line5","line6"]
filename = "data.txt"
appendtofile(filename,data)

## Numpy

* Advantages of numpy

* Numpy is an advance library.
* Numpy means numerical python.
* Numpy is to perform mathematical and stastical operations
* The values are represented in the form of rows and columns
these all are uses.
* Advantages of numpy when compared to list
         * it takes less time
          *  performance is high
           * occupies less memory
        

In [1]:
import numpy as np

In [10]:
## creating the array
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
## creating a array in particular range
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
### checking the number of elements
a.size

9

In [13]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a2= np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
a2.size

8

In [42]:
a2=np.array([[1,2,3,4,],[5,6,7,8]],dtype = complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [52]:

### comparision of two arrays
a=np.array([[1,2,3,4,],[5,6,7,8]]) 
b=np.array([[4,5,6,7],[3,4,5,6]])



In [44]:
a2.dtype

dtype('complex128')

In [46]:
a.dtype

dtype('int32')

In [53]:
a>b

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [54]:
a<b

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [55]:
a==b

array([[False, False, False, False],
       [False, False, False, False]])

In [56]:
a-b

array([[-3, -3, -3, -3],
       [ 2,  2,  2,  2]])

In [57]:
a+b

array([[ 5,  7,  9, 11],
       [ 8, 10, 12, 14]])

In [58]:
a**b

array([[     1,     32,    729,  16384],
       [   125,   1296,  16807, 262144]], dtype=int32)

In [59]:
a%b

array([[1, 2, 3, 4],
       [2, 2, 2, 2]], dtype=int32)

In [60]:
a*b

array([[ 4, 10, 18, 28],
       [15, 24, 35, 48]])

In [61]:
a^b

array([[ 5,  7,  5,  3],
       [ 6,  2,  2, 14]], dtype=int32)

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.ones(3)

array([1., 1., 1.])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
a[0]

array([1, 2, 3, 4])

In [69]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
a[0:1,1:2]

array([[2]])

In [72]:
a[1:2,2:3]

array([[7]])

In [73]:
a[:,1:3]

array([[2, 3],
       [6, 7]])

In [74]:
a[0,1]

2

In [75]:
a[:,2:3]

array([[3],
       [7]])

In [80]:
a[:,0:2]

array([[1, 2],
       [5, 6]])

In [81]:
a.shape

(2, 4)

In [84]:
a.ndim

2

In [85]:
a.nbytes

32

In [86]:
a.itemsize

4

In [90]:
b= np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [93]:
b= np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [94]:
b= np.arange(3,9)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [103]:
b= np.arange(3,9)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [104]:
min(b)

3

max(b

In [105]:
max(b)

8

In [106]:
np.std(b)

1.707825127659933

In [107]:
np.sum(b)

33

In [108]:
np.mean(b)

5.5

In [110]:
np.var(b)

2.9166666666666665

In [111]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [112]:
b

array([3, 4, 5, 6, 7, 8])

In [114]:
np.argmin(b)

0

In [115]:
np.argmax(b)

5

In [117]:
np.transpose(b)

array([3, 4, 5, 6, 7, 8])

In [120]:

a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [121]:
b=a

# binary to decimal

In [4]:
b=int(input())
d=0
i=0
while b!=0:
    binary=b%10
    d=d+binary*(2**i)
    b=b//10
    i=i+1
print(d)    

1011
11


# decimal to binary

In [3]:
s="12345"
def reversestring(s):
    return s[-1::-1]
reversestring(s)

'54321'

In [4]:
n=int(input())
s=0
while (n>0):
        r=n%10
        s=s+r
        n=n//10
        print("sum of digits",s)

234
sum of digits 4
sum of digits 7
sum of digits 9
